services:
  # Servicio 1: Base de Datos
  db:
    image: postgres:15-alpine
    container_name: openmind_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: open_mind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio 2: Backend Spring Boot
  app:
    build: ./OpenMindBack
    container_name: openmind_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/open_mind
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  # Servicio 3: Frontend Angular
  #frontend:
    #build: ./OpenMindFront
    #container_name: openmind_frontend
    #ports:
     # - "4200:80"
   # depends_on:
    #  - app

volumes:
  postgres_data:
